### ISSUE TITLE
Not able to connect live openBCI.

### ISSUE THREAD

**Issue by rakeshbci** [neuralbertatech/openComp2020#2]
I am using cyton to connect on Windows 10 but I am getting this error.

NAT Brain Drone Controller
1: Connect BCI
2: Collect Data
3: Train Model
4: Connect Drone
5: Fly!

1: Connect BCI
Serial established
Skipped 2 bytes before start found
Traceback (most recent call last):
  File "masterController.py", line 821, in <module>
    board.start_stream(bciStream)
  File "C:\Users\rakes\miniconda3\lib\site-packages\pyOpenBCI\cyton.py", line 269, in start_stream
    call(sample)
  File "masterController.py", line 774, in bciStream
    checkForRailedChannels(data)
  File "masterController.py", line 303, in checkForRailedChannels
    value = line[0]
IndexError: list index out of range

**Comment by james-bole-pan** [comment]
Any updates on this issue?
